name: setup-engines
description: setup engines in package.json automatically

runs:
  using: "composite"
  steps:
    - id: json
      shell: bash
      run: echo "txt=$(cat package.json | jq -c '.engines')" >> $GITHUB_OUTPUT

    - id: engines
      shell: bash
      run: |
        echo "node=${{ fromJSON(steps.json.outputs.txt).node }}" >> $GITHUB_OUTPUT
        echo "yarn=${{ fromJSON(steps.json.outputs.txt).yarn }}" >> $GITHUB_OUTPUT
        echo "pnpm=${{ fromJSON(steps.json.outputs.txt).pnpm }}" >> $GITHUB_OUTPUT

    - name: setup node
      if: steps.engines.outputs.node != ''
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.engines.outputs.node }}

    - name: setup yarn
      if: steps.engines.outputs.yarn != ''
      shell: bash
      run: npm i -g yarn@${{ steps.engines.outputs.yarn }}

    - name: setup pnpm
      if: steps.engines.outputs.pnpm != ''
      shell: bash
      run: npm i -g pnpm@${{ steps.engines.outputs.pnpm }}
